
name: Java CI with Maven

on:
  push:
    branches: [ "feature/git-commit-id" ]
  pull_request:
    branches: [ "feature/git-commit-id" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Up jdk 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: mvn clean install 
    - run: mkdir staging && cp -r target/* staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
            
    
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: pavirat43/springboot-image
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

